name: dating_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0
  image_picker: ^1.1.2
  smooth_page_indicator: ^1.2.1
  google_fonts: ^6.2.1
  http: 1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.1
  rename: ^3.1.0

flutter:
  uses-material-design: true
  
  assets:
    - images/
    
  fonts:
    - family: Josefin Sans
      fonts:
        - asset: fonts/JosefinSans-Regular.ttf
        - asset: fonts/JosefinSans-Bold.ttf
          weight: 700
        - asset: fonts/JosefinSans-Light.ttf
          weight: 300
        - asset: fonts/JosefinSans-Medium.ttf
          weight: 500
        - asset: fonts/JosefinSans-SemiBold.ttf
          weight: 600

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/logo.jpg"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "images/logo.jpg"
    background_color: "#FFE4F4"
    theme_color: "#FFE4F4"
  windows:
    generate: true
    image_path: "images/logo.jpg"
    icon_size: 48
  macos:
    generate: true
    image_path: "images/logo.jpg"

